# Generated by Django 4.2.5 on 2023-09-08 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_payment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_opened',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
