# Generated by Django 4.2.5 on 2023-09-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_last_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_active',
            field=models.BooleanField(default=False),
        ),
    ]
