# Generated by Django 4.2.5 on 2023-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_payment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='page',
        ),
        migrations.AddField(
            model_name='book',
            name='epub_viewer_key',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='position',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
