# Generated by Django 4.2.5 on 2023-09-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_bookmark_position_bookmark_is_custom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='epub_viewer_key',
        ),
        migrations.AddField(
            model_name='book',
            name='last_page',
            field=models.IntegerField(default=1),
        ),
    ]
