# Generated by Django 4.2.5 on 2023-09-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_book_epub_viewer_key_book_last_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='last_page',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='page',
        ),
        migrations.AddField(
            model_name='book',
            name='last_location',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='location',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
