# Generated by Django 4.2.5 on 2023-09-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_book_last_page_remove_bookmark_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_location',
            field=models.CharField(blank=True, null=True),
        ),
    ]
