# Generated by Django 4.2.5 on 2023-09-17 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_payment',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 11, 55, 59, 217662, tzinfo=datetime.timezone.utc)),
        ),
    ]
